[package]
name = "rs-ls"
version = "0.1.0"
authors = ["Jake Goldsborough <jake.goldsborough@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
colored = "1.7"
chrono = "0.4"
structopt = "0.2"
